# .readthedocs.yml
build:
  image: stable
conda:
  environment: doc/environment.yml
python:
    version: 3.7

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py