/*
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
*/

/**
  Footer: The website/core/Footer.js file 
  is a React component that acts as the footer for the site 
  generated by Docusaurus and should be customized by the user.
*/

const React = require('react');

class Footer extends React.Component {
  docUrl(doc, language) {
    const baseUrl = this.props.config.baseUrl;
    const docsUrl = this.props.config.docsUrl;
    const docsPart = `${docsUrl ? `${docsUrl}/` : ''}`;
    // TODO: enable lang props for docs after set up Crowdin
    // const langPart = `${language ? `${language}/` : ''}`;
    const langPart = ''
    return `${baseUrl}${docsPart}${langPart}${doc}`;
  }

  pageUrl(doc, language) {
    const baseUrl = this.props.config.baseUrl;
    return baseUrl + (language ? `${language}/` : '') + doc;
  }

  render() {
    return (
      <footer className="nav-footer" id="footer">
        <section className="sitemap">
          <a href={this.props.config.baseUrl} className="nav-home">
            {this.props.config.footerIcon && (
              <img
                src={this.props.config.baseUrl + this.props.config.footerIcon}
                alt={this.props.config.title}
                width="66"
                height="58"
              />
            )}
          </a>
          <div>
            <h5>Docs</h5>
            <a href={this.docUrl('installation', this.props.language)}>
              Getting Started
            </a>
            <a href={this.docUrl('device', this.props.language)}>
              Guides
            </a>
            <a href={this.pageUrl('#', this.props.language)}>
              API Reference (coming soon)
            </a>
            <a href={this.docUrl('model-zoo-cnn-cifar10', this.props.language)}>
              Model Zoo
            </a>
            <a href={this.docUrl('download-singa', this.props.language)}>
              Development
            </a>
          </div>
          <div>
            <h5>Community</h5>
            <a href={this.pageUrl('users.html', this.props.language)}>
              User Showcase
            </a>
            <a href={this.docUrl('history-singa', this.props.language)}>
              SINGA History
            </a>
            <a href={this.docUrl('team-list', this.props.language)}>
              SINGA Team
            </a>
            <a href={`${this.props.config.baseUrl}news`}>
              SINGA News
            </a>
            <a href={this.props.config.repoUrl}>GitHub</a>
            <div className="social">
              <a
                className="github-button" // part of the https://buttons.github.io/buttons.js script in siteConfig.js
                href={this.props.config.repoUrl}
                data-count-href="/apache/singa/stargazers"
                data-show-count="true"
                data-count-aria-label="# stargazers on GitHub"
                aria-label="Star this project on GitHub">
                {this.props.config.organizationName}/
                {this.props.config.projectName}
              </a>
            </div>
            {this.props.config.twitterUsername && (
              <div className="social">
                <a
                  href={`https://twitter.com/${this.props.config.twitterUsername}`}
                  className="twitter-follow-button">
                  Follow @{this.props.config.twitterUsername}
                </a>
              </div>
            )}
          </div>
          <div>
            <h5>Apache Software Foundation</h5>
            <a
              href="https://apache.org/"
              target="_blank"
              rel="noreferrer noopener">
              Foundation
            </a>
            <a
              href="http://www.apache.org/licenses/"
              target="_blank"
              rel="noreferrer noopener">
              License
            </a>
            <a
              href="http://www.apache.org/foundation/sponsorship.html"
              target="_blank"
              rel="noreferrer noopener">
              Sponsorship
            </a>
            <a
              href="http://www.apache.org/foundation/thanks.html"
              target="_blank"
              rel="noreferrer noopener">
              Thanks
            </a>
            <a
              href="http://www.apache.org/events/current-event"
              target="_blank"
              rel="noreferrer noopener">
              Events
            </a>
            <a
              href="http://www.apache.org/security/"
              target="_blank"
              rel="noreferrer noopener">
              Security
            </a>
          </div>
        </section>

        <div style={{ width: "100%", textAlign: "center" }}>
          <a
            href="https://apache.org/"
            target="_blank"
            rel="noreferrer noopener"
            className="ApacheOpenSource">
            <img
              src={`${this.props.config.baseUrl}img/asf_logo_wide.svg`}
              alt="Apache Open Source"
            />
          </a>
          <section
            className="copyright"
            style={{ maxWidth: "50%", margin: "0 auto" }}
          >
            {this.props.config.copyright}
          </section>
        </div>
      </footer>
    );
  }
}

module.exports = Footer;
