
FIND_PACKAGE(CUDA 5.5 QUIET)

IF(NOT CUDA_FOUND)
    return()
ENDIF()

SET(HAVE_CUDA TRUE)
MESSAGE(STATUS "Found cuda_v${CUDA_VERSION}")
#ADD_DEFINITIONS(-DUSE_CUDA)
#message(STATUS "linking: ${CUDA_CUDART_LIBRARY} ${CUDA_curand_LIBRARY} ${CUDA_CUBLAS_LIBRARIES}")

IF(USE_CUDNN)
#include(cmake/Modules/Cudnn.cmake)
    FIND_PACKAGE(CUDNN REQUIRED)
    INCLUDE_DIRECTORIES(SYSTEM ${CUDNN_INCLUDE_DIR})
    LIST(APPEND SINGA_LINKER_LIBS ${CUDNN_LIBRARIES})
    #ADD_DEFINITIONS(-DUSE_CUDNN)
    #ADD_DEFINITIONS(-DCUDNN_VERSION_MAJOR=${CUDNN_VERSION_MAJOR})
ENDIF()

INCLUDE_DIRECTORIES(SYSTEM ${CUDA_INCLUDE_DIRS})
LIST(APPEND SINGA_LINKER_LIBS ${CUDA_CUDART_LIBRARY} ${CUDA_curand_LIBRARY} ${CUDA_CUBLAS_LIBRARIES})
#MESSAGE(STATUS "libs " ${SINGA_LINKER_LIBS})
