#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Native-MacOS

on:
  push:
  pull_request:

jobs:
  build-cpptest-cpu:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: install-build-dependencies
        run: |
         brew install protobuf abseil swig lmdb numpy
         echo "BREW_PREFIX=$(brew --prefix)" >> "$GITHUB_ENV"
         echo "PROTOBUF_ROOT=$(brew --prefix protobuf)" >> "$GITHUB_ENV"
         echo "ABSL_ROOT=$(brew --prefix abseil)" >> "$GITHUB_ENV"
         wget https://github.com/oneapi-src/oneTBB/releases/download/v2020.1/tbb-2020.1-mac.tgz
         mkdir /tmp/tbb
         tar zxvf tbb-2020.1-mac.tgz -C /tmp/tbb --strip-components=1
         echo "TBB_ROOT=/tmp/tbb" >> "$GITHUB_ENV"
         python -m pip install numpy
      - name: configure
        run: |
         export CMAKE_INCLUDE_PATH="$PROTOBUF_ROOT/include:$ABSL_ROOT/include:$BREW_PREFIX/opt/openblas/include:$CMAKE_INCLUDE_PATH"
         export CMAKE_LIBRARY_PATH="$PROTOBUF_ROOT/lib:$ABSL_ROOT/lib:$BREW_PREFIX/opt/openblas/lib:$CMAKE_LIBRARY_PATH"
         export CXXFLAGS="-I$PROTOBUF_ROOT/include -I$ABSL_ROOT/include -I$(python -c 'import numpy; print(numpy.get_include())') $CXXFLAGS"
         mkdir build && cd build && cmake -DUSE_PYTHON3=YES -DENABLE_TEST=YES -DUSE_DNNL=NO -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ..
      - name: build
        run: |
         export LD_LIBRARY_PATH="$BREW_PREFIX/opt/openblas/lib:/tmp/tbb/lib:$LD_LIBRARY_PATH"
         export DYLD_LIBRARY_PATH="$BREW_PREFIX/opt/openblas/lib:/tmp/tbb/lib:$DYLD_LIBRARY_PATH"
         cd build && make
      - name: C++ test
        run: |
         export LD_LIBRARY_PATH="$BREW_PREFIX/opt/openblas/lib:/tmp/tbb/lib:$LD_LIBRARY_PATH"
         export DYLD_LIBRARY_PATH="$BREW_PREFIX/opt/openblas/lib:/tmp/tbb/lib:$DYLD_LIBRARY_PATH"
         build/bin/test_singa
